swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/account/checking:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary : User checking API
      description : API for fetching a user account
      produces : 
        - application/json
      responses : 
        "200" : 
          description : User account retrieved Successfully
          shema: 
            $ref: "#/definitions/AccountResponse"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account/savings:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary : User savings API
      description : API for fetching a user account
      produces : 
        - application/json
      responses : 
        "200" : 
          description : User account retrieved Successfully
          shema: 
            $ref: "#/definitions/AccountResponse"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account/creditCard:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary : User creditCard API
      description : API for fetching a user account
      produces : 
        - application/json
      responses : 
        "200" : 
          description : User account retrieved Successfully
          shema: 
            $ref: "#/definitions/AccountResponse"
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

      